version: "2.2"
services:

  webapp:
    build: ./docker
    volumes: 
      - ./app:/var/www:delegated
    ports: 
      - "8085:80"
    links: 
      - elastic
  
  elastic:
    image: elasticsearch:7.7.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports: 
      - "9200:9200"
      - "9300:9300"