parameters:
    env(ELASTICSEARCH_HOST): 'http://elastic:9200'

api_platform:

    mapping:
        paths: ['%kernel.project_dir%/src/Model']

    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']
        mapping:
            App\Model\Tweet:
                index: tweet
                type: _doc
    
    patch_formats:    
        json: ['application/merge-patch+json']
    
    swagger:
        versions: [3]
